name: Node.js CI - Angular Frontend

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build --prod  

    - name: Run unit tests
      run: npm test -- --watch=false --browsers=ChromeHeadless  
      env:
        CI: true  
